# Generated by Django 3.1.6 on 2021-03-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Enter your name', max_length=30)),
                ('phone_no', models.IntegerField(max_length=13)),
                ('email_add', models.CharField(default='abc@gmail.com', max_length=50)),
                ('courier_add', models.TextField(default='1/2, avenue park, new york, us', max_length=150)),
                ('zip_code', models.IntegerField(max_length=10)),
            ],
            options={
                'verbose_name': 'Orders',
                'verbose_name_plural': 'Orderss',
            },
        ),
    ]
